name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.TOKEN }}
        issue-message: 'Hi! This seems to be your first issue! Please make sure to provide infomation such as logs and version infomation if you are reporting a bug.'
        pr-message: "Thanks for creating your first PR here! If your PR doesn't modify the Mojangster code it will automatically be closed - fixing a typo on the readme file does not count as an effective contribution."
